apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-springboot
  labels:
    app: multicloud-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicloud-springboot
  template:
    metadata:
      labels:
        app: multicloud-springboot
    spec:
      containers:
      - name: app
        image: your-registry/your-image:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: multicloud-springboot
spec:
  type: NodePort
  selector:
    app: multicloud-springboot
  ports:
  - port: 8080
    nodePort: 30080
